-- Build SQLite3
--   static or shared library
--   Multi cipher encryption support
--   Debug or Release
--   Lin32 or Lin64

-- Target directory for the build files generated by premake5
newoption {
  trigger     = "builddir",
  value       = "build",
  description = "Directory for the generated build files"
}

BUILDDIR = _OPTIONS["builddir"] or "build"

-- SQLite3Secure workspace

workspace "SQLite3Secure"
  configurations { "Debug", "Release" }
  platforms { "Linux32", "Linux64" }
  location(BUILDDIR)

  filter { "platforms:Linux32" }
    system "Linux"
    architecture "x86"
    targetsuffix "_x86"

  filter { "platforms:Linux64" }
    system "Linux"
    architecture "x86_64"
    targetsuffix "_x86_64"

  filter { "configurations:Debug*" }
    defines {
      "DEBUG",
    }
    symbols "On"

  filter { "configurations:Release*" }
    defines {
      "NDEBUG"
    }
    optimize "On"

  filter {}

-- SQLite3 static library
project "sqlite3lib"
  language "C++"
  kind "StaticLib"

  toolset("gcc")
  makesettings { "include config.gcc" }

  files { "src/sqlite3secure.c", "src/*.h" }
  vpaths {
    ["Header Files"] = { "**.h" },
    ["Source Files"] = { "**/sqlite3secure.c", "**.def" }
  }
  characterset ("Unicode")
  flags { "StaticRuntime" }

  location( BUILDDIR )
  targetname "sqlite3"

  defines {
    "SQLITE_THREADSAFE=1",
    "SQLITE_DQS=0",
    "SQLITE_MAX_ATTACHED=10",
    "SQLITE_ENABLE_EXPLAIN_COMMENTS",
    "SQLITE_SOUNDEX",
    "SQLITE_ENABLE_COLUMN_METADATA",
    "SQLITE_HAS_CODEC=1",
    "CODEC_TYPE=CODEC_TYPE_CHACHA20",
    "SQLITE_SECURE_DELETE",
    "SQLITE_ENABLE_FTS3",
    "SQLITE_ENABLE_FTS3_PARENTHESIS",
    "SQLITE_ENABLE_FTS4",
    "SQLITE_ENABLE_FTS5",
    "SQLITE_ENABLE_JSON1",
    "SQLITE_ENABLE_RTREE",
    "SQLITE_ENABLE_GEOPOLY",
    "SQLITE_CORE",
    "SQLITE_ENABLE_EXTFUNC",
    "SQLITE_ENABLE_CSV",
--    "SQLITE_ENABLE_SHA3",
    "SQLITE_ENABLE_CARRAY",
--    "SQLITE_ENABLE_FILEIO",
    "SQLITE_ENABLE_SERIES",
    "SQLITE_TEMP_STORE=2",
    "SQLITE_USE_URI",
    "SQLITE_USER_AUTHENTICATION",
-- Compatibility with official SQLite3 shell    
    "SQLITE_ENABLE_DBSTAT_VTAB",
    "SQLITE_ENABLE_STMTVTAB",
    "SQLITE_ENABLE_UNKNOWN_SQL_FUNCTION"
  }

  -- Intermediate directory

    objdir (BUILDDIR .. "/obj-gcc")

  -- Target directory
  filter { "configurations:Debug*" }
    targetdir "bin-gcc/lib/debug"

  filter { "configurations:Release*" }
    targetdir "bin-gcc/lib/release"

-- SQLite3 shared library
project "sqlite3so"
  language "C++"
  kind "SharedLib"

  toolset("gcc")
  makesettings { "include config.gcc" }

  files { "src/sqlite3secure.c", "src/*.h", "src/sqlite3.def" }
  filter {}
  vpaths {
    ["Header Files"] = { "**.h" },
    ["Source Files"] = { "**/sqlite3secure.c", "**.def"}
  }
  characterset ("Unicode")
  flags { "StaticRuntime" }

  location( BUILDDIR )
  targetname "sqlite3"

  defines {
    "SQLITE_THREADSAFE=1",
    "SQLITE_DQS=0",
    "SQLITE_MAX_ATTACHED=10",
    "SQLITE_SOUNDEX",
    "SQLITE_ENABLE_COLUMN_METADATA",
    "SQLITE_HAS_CODEC=1",
    "CODEC_TYPE=CODEC_TYPE_CHACHA20",
    "SQLITE_SECURE_DELETE",
    "SQLITE_ENABLE_FTS3",
    "SQLITE_ENABLE_FTS3_PARENTHESIS",
    "SQLITE_ENABLE_FTS4",
    "SQLITE_ENABLE_FTS5",
    "SQLITE_ENABLE_JSON1",
    "SQLITE_ENABLE_RTREE",
    "SQLITE_ENABLE_GEOPOLY",
    "SQLITE_CORE",
    "SQLITE_ENABLE_EXTFUNC",
    "SQLITE_ENABLE_CSV",
    "SQLITE_ENABLE_SHA3",
    "SQLITE_ENABLE_CARRAY",
    "SQLITE_ENABLE_FILEIO",
    "SQLITE_ENABLE_SERIES",
    "SQLITE_TEMP_STORE=2",
    "SQLITE_USE_URI",
    "SQLITE_USER_AUTHENTICATION"
  }

  -- Intermediate directory

    objdir (BUILDDIR .. "/obj-gcc")

  -- Target directory

  filter { "configurations:Debug*" }
    targetdir "bin-gcc/so/debug"
  filter { "configurations:Release*" }
    targetdir "bin-gcc/so/release"

-- SQLite3 Shell
project "sqlite3shell"
  kind "ConsoleApp"
  language "C++"

  toolset("gcc")
  makesettings { "include config.gcc" }

  vpaths {
    ["Header Files"] = { "**.h" },
    ["Source Files"] = { "**.c" }
  }
  files { "src/sqlite3.h", "src/shell.c"}
  characterset ("Unicode")
  flags { "StaticRuntime" }
  links { "sqlite3lib" }
  links { "pthread" }
  links { "dl" }

  location( BUILDDIR )

  defines {
    "SQLITE_SHELL_IS_UTF8",
    "SQLITE_HAS_CODEC=1",
    "SQLITE_USER_AUTHENTICATION"
  }

  -- Intermediate directory

    objdir (BUILDDIR .. "/obj-gcc")

  -- Target directory
  filter { "configurations:Debug*" }
    targetdir "bin-gcc/lib/debug"

  filter { "configurations:Release*" }
    targetdir "bin-gcc/lib/release"
